# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/hackthesat/fpga/hts_fpga/ztec_project/ztec_project.srcs/sources_1/ip/ram_16x8k_sp_2/ram_16x8k_sp_2.xci
# IP: The module: 'ram_16x8k_sp_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/hackthesat/fpga/hts_fpga/ztec_project/ztec_project.srcs/sources_1/ip/ram_16x8k_sp_2/ram_16x8k_sp_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_16x8k_sp_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/user/hackthesat/fpga/hts_fpga/ztec_project/ztec_project.srcs/sources_1/ip/ram_16x8k_sp_2/ram_16x8k_sp_2.xci
# IP: The module: 'ram_16x8k_sp_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/hackthesat/fpga/hts_fpga/ztec_project/ztec_project.srcs/sources_1/ip/ram_16x8k_sp_2/ram_16x8k_sp_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_16x8k_sp_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
