# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/hackthesat/fpga/new_project/ztec_project/ztec_project.srcs/sources_1/ip/ram_16x16k_sp_dmem/ram_16x16k_sp_dmem.xci
# IP: The module: 'ram_16x16k_sp_dmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/hackthesat/fpga/new_project/ztec_project/ztec_project.srcs/sources_1/ip/ram_16x16k_sp_dmem/ram_16x16k_sp_dmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_16x16k_sp_dmem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/user/hackthesat/fpga/new_project/ztec_project/ztec_project.srcs/sources_1/ip/ram_16x16k_sp_dmem/ram_16x16k_sp_dmem.xci
# IP: The module: 'ram_16x16k_sp_dmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/hackthesat/fpga/new_project/ztec_project/ztec_project.srcs/sources_1/ip/ram_16x16k_sp_dmem/ram_16x16k_sp_dmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_16x16k_sp_dmem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
