# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/leon3-ztec_2_13/leon3mp.xdc

# IP: ip/ram_16x16k_sp_pmem/ram_16x16k_sp_pmem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_16x16k_sp_pmem || ORIG_REF_NAME==ram_16x16k_sp_pmem} -quiet] -quiet

# IP: ip/mig/mig.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig || ORIG_REF_NAME==mig} -quiet] -quiet

# XDC: ip/ram_16x16k_sp_pmem/ram_16x16k_sp_pmem_ooc.xdc

# XDC: ip/mig/mig/user_design/constraints/mig.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig || ORIG_REF_NAME==mig} -quiet] -quiet

# XDC: ip/mig/mig/user_design/constraints/mig_ooc.xdc
