for i in 0..5

  cmd("PL_IF TAKE_IMG with CCSDS_STREAMID 6617, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 2, CCSDS_FUNCCODE 7, CCSDS_CHECKSUM 0, TAKE_IMG 0")
  sleep(90)
  cmd("PL_IF GET_IMAGE_SIZE with CCSDS_STREAMID 6617, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 2, CCSDS_FUNCCODE 7, CCSDS_CHECKSUM 0, IMAGE_SIZE 5")
  sleep(30)
  cmd("PL_IF DLINK_IMG with CCSDS_STREAMID 6617, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 2, CCSDS_FUNCCODE 7, CCSDS_CHECKSUM 0, DLINK_IMG 48")
  sleep(180)
  cmd("CF PLAYBACK_FILE with CCSDS_STREAMID 6323, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 149, CCSDS_FUNCCODE 2, CCSDS_CHECKSUM 0, CLASS 1, CHANNEL 0, PRIORITY 0, PRESERVE 1, PEER_ID '0.21', SRC_FILENAME '/cf/img.png', DEST_FILENAME '/home/jlatimer/opensatkit/test_strip#{i}.png'")
  sleep(180)
 
end