dwell_time = 60
for i in 0..10
cmd("EYASSAT_IF ADCS_CTRL_ALG with CCSDS_STREAMID 6613, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 5, CCSDS_FUNCCODE 5, CCSDS_CHECKSUM 0, CODE 'ac', CTRL_ALG PID")
cmd("EYASSAT_IF ADCS_WHEEL_SPD with CCSDS_STREAMID 6613, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 7, CCSDS_FUNCCODE 6, CCSDS_CHECKSUM 0, CODE 'aw', SPD 3.5")
sleep(dwell_time)
cmd("EYASSAT_IF ADCS_WHEEL_SPD with CCSDS_STREAMID 6613, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 7, CCSDS_FUNCCODE 6, CCSDS_CHECKSUM 0, CODE 'aw', SPD 5.0")
sleep(dwell_time)
cmd("EYASSAT_IF ADCS_WHEEL_SPD with CCSDS_STREAMID 6613, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 7, CCSDS_FUNCCODE 6, CCSDS_CHECKSUM 0, CODE 'aw', SPD -3.5")
sleep(dwell_time)
cmd("EYASSAT_IF ADCS_WHEEL_SPD with CCSDS_STREAMID 6613, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 7, CCSDS_FUNCCODE 6, CCSDS_CHECKSUM 0, CODE 'aw', SPD -5.0")
sleep(dwell_time)
end
cmd("EYASSAT_IF ADCS_CTRL_ALG with CCSDS_STREAMID 6613, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 5, CCSDS_FUNCCODE 5, CCSDS_CHECKSUM 0, CODE 'ac', CTRL_ALG DEFAULT")